### PR TITLE
feat: add Arbitrum One as supported chain

### PR DESCRIPTION
**Pull request by r1ck12**
# Overview
Minor change to update the `RelayChains` table, adding Arbitrum One as a new supported chain.

### CODE REVIEW

**Comment by r1ck12** [comment]
Link T-18018

**Comment by ArtSabintsev** [comment]
@r1ck12 can we please do this alphabetically?

Also, do we have a public endpoint? I was looking to have this document updated as well: https://docs.pokt.network/use/public-rpc/

**Comment by r1ck12** [comment]
> @r1ck12 can we please do this alphabetically?
> 
> Also, do we have a public endpoint? I was looking to have this document updated as well: https://docs.pokt.network/use/public-rpc/

of course, will do a new push with it ordered alphabetically. Also, I think Sean or Gabi knows about the endpoint. thank you

**Comment by ArtSabintsev** [comment]
Can you work with @vlad-she do get all the missing chains in both of these documents? I think Celo is missing in both documents.

**Comment by r1ck12** [comment]
> 



> Can you work with @vlad-she do get all the missing chains in both of these documents? I think Celo is missing in both documents.

We can organize them into a single commit or task. Just need to know what the values are for the Supported Blockchains and RPC Endpoints tables. Link T-18328

**Review by jessicadaugherty — APPROVED** [review]

**Review by ArtSabintsev — APPROVED** [review]

**Pull request merged**
