### PR TITLE
Git-Book - V1.0 Utility - Incentives - Quality Based

### PR DESCRIPTION
**Pull request by jessicadaugherty**
Proposing to include an Incentives diagram for V1.0 Quality Based Servicer Rewards

### CODE REVIEW

**Comment by Olshansk** [comment]
@jessicadaugherty Would you be able to share the source file for whatever tool you used to generate the image? That way others would be able to edit it as well if needed.

**Comment by jessicadaugherty** [comment]
@Olshansk absolutely! I made this using diagrams.net. Here is a [link](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=POKT%20V1.0%20Utility%20Rewards%20XML.drawio#R7VzbcuI4EP0aqnYfQlm%2B85iQbDK7sztTYasmeVSwAM8ayyOLAPn6kWwZXyTALGBzmYcQqyXL4pxWd6vbScfoTxePBEaTv7GHgo6ueYuOcd%2FRdccC7JMLlqnAsO1UMCa%2Bl4pALhj4H0gINSGd%2BR6KSwMpxgH1o7JwiMMQDWlJBgnB8%2FKwEQ7KT43gGEmCwRAGsvSb79FJKnUtLZc%2FIX88yZ4MNNEzhdlgIYgn0MPzgsh46Bh9gjFNr6aLPgo4dhku6X1%2FrOldLYygkNa54c%2BXUf%2B78dV9GL5akILl8nN4eyNmeYfBTHxhsVi6zBBAoXfLgWStEIdMeDeh04C1ALskeBZ6iD9BYy15SWJ%2B5JVQFgt8RHiKKFmyAfMc2wzaSQHWTEZQAKn%2FXuYGCorHq%2BlWT%2FiKfbYSXRPaqFvpHZkumlp5hhjPyBCJm4pQVuZxt01EIRkjKk3ELgrfOhclTO3Ami6x9q5JvFG0oGWyYkrwf6iPA0xyMkd%2BEFREMPDHIWsOGY2Iye%2FeEaE%2B2xO3omPqex5%2FzN184lM0iOCQP3PODICkEiMcUrGrgblJRfgz0GKjkoheQyuBn%2BlGQYVshQoZ2nptKfGzKxmGTAboXhEd1b1gO%2B3yYdYwaUHA%2FMc6xAoUwThKncrIX3AMJfyKdHV04w143kiTuGU9QHOMHjoM4gDo3TLott3NaCjADgwF7uBowGeevQg0s%2FsD0cSETvAYhzB4yKUV9czHfMY4EiR8R5QuBehwRnGZIrTw6Yu4nV%2B%2F8msGT9q6XxS67peKXQA2cZI6hE2W2Kjp4Pb0XMBxKpTrWrM%2Bx%2B61yS7YgV1GIlm%2B5AN58zWbgzfy25LW8bQipWTDQKt3aPWpu4NHofEB%2F%2Fr0ZfbvF%2Bg8xk9Pz9%2BiG%2BtcNvD%2FpViJ9uE4VoLaKqOtmuQmNm0bjOoNMbpxlZvimwNHNSPoOXCoimreTNvSDhXW9%2FIgJvNxQI7t3VXsU4xqcunhAZcDygEi7z4DV9ee0RwS73qCfVOT4hBDGXs2G%2FKrYn47oAKDEjf2jxnOOm7iBJ1bNgCAaJF3sqsx%2F%2F2MIoJiBle6sXUNj%2FhkfjgOUvYDuOxPoB%2FyLsI%2BGGI3H5xJXbuNIvY5QHHs4zABh2HDvjz7uZsRLuljNBr5Qx8lS0ymBtm6GQ7p0tOFnIGGbUwA1dcwKdC1TdkIOHqT6mXZ6ywAic%2BAGDPp5SqM%2BSw3vQMxVTHWpt7ywd9yftG0PV0GFD61WZp62wOYM0%2FQ2LpkxJiTtCXcm07QyHnjxIPFiZ8i7xxA7gu5wbUyR%2FRGcmeYxDrFISe%2FqTae43fIuOlSbAqAOuemKePT43Eqhz5KTvlSt3AqhlwLp7YJlJwqtmke9B6a0%2FUZg1M3kBLQCjrWhw62tJ%2BatpDrT%2FYXjbxpqVxT%2B7UDOauhNmPbXZN%2BXa5Jd%2Byu69YzY27XadQ3WfVIBdt9E7gu32Q61aB9TbBhHI1RpX10L94%2BAlApZ7vycalhp9Rq4W3%2FsuquuXl1SGSoWdu3rOqW95kF8g11%2BLqq%2BpvJr4pcWInm6GpRpwhn7ak%2F%2BwX0oE2OT7ewuienbqucKlzfZe3bVjjttcrpCddW94pqFLVVS89dXUPlVTXmF1Ze3e90DirxSIMvt27wmxcd8duVAgmL%2BLsaaDvoB3LNUXVCjpgPYaP6%2BUFZU2dIRMn5GVKUDqyRSDm7M%2Fd%2BJ79qPdNQ6wFodP%2FJNc1aauDU1AJjuxqAJGF4RYpgm9XXq1WlbaA1WhK4%2FMyLbufpydMyxWdRsN4v7rAlH9g26tkbPrtavl5NywdqOED9yiyfzvZbVonZaPry00Qj1m%2BVQN9RF9yaunCRVaX9DIJzej4wM7un%2FJbn%2Bb%2B8uZfaVNLphia7kaO9uqnWGVVG5xA6U7Qh7Bvx%2B1fZCu0fxFBkv78S7M2GiIt%2B60M%2B%2FuHHDPJFs2nglFMiFESc237vsstPfCCd%2BLxMihZsGNfCfmdVBE3VM8JM5d4SBSXJc%2FnwOSIonV0sly%2BTP7%2Bw%2FF8aWtBQWz%2BehrJm%2Ftf9abko%2FxcJxsNP) that will allow you to edit a copy of this and modify as needed. Lmk if you have any questions.

**Comment by Olshansk** [comment]
I was thinking that in the markdown source file, below the line where the image is embedded, we could add a comment so that editors can see it but readers cannot.

```
![image](https://user-images.githubusercontent.com/55156619/154539548-91731703-3f23-4a27-b758-7d7268c50df4.png)
<!---
Image was generated using the following link from diagrams.net: https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=POKT%20V1.0%20Utility%20Rewards%20XML.drawio#R7VzbcuI4EP0aqnYfQlm%2B85iQbDK7sztTYasmeVSwAM8ayyOLAPn6kWwZXyTALGBzmYcQqyXL4pxWd6vbScfoTxePBEaTv7GHgo6ueYuOcd%2FRdccC7JMLlqnAsO1UMCa%2Bl4pALhj4H0gINSGd%2BR6KSwMpxgH1o7JwiMMQDWlJBgnB8%2FKwEQ7KT43gGEmCwRAGsvSb79FJKnUtLZc%2FIX88yZ4MNNEzhdlgIYgn0MPzgsh46Bh9gjFNr6aLPgo4dhku6X1%2FrOldLYygkNa54c%2BXUf%2B78dV9GL5akILl8nN4eyNmeYfBTHxhsVi6zBBAoXfLgWStEIdMeDeh04C1ALskeBZ6iD9BYy15SWJ%2B5JVQFgt8RHiKKFmyAfMc2wzaSQHWTEZQAKn%2FXuYGCorHq%2BlWT%2FiKfbYSXRPaqFvpHZkumlp5hhjPyBCJm4pQVuZxt01EIRkjKk3ELgrfOhclTO3Ami6x9q5JvFG0oGWyYkrwf6iPA0xyMkd%2BEFREMPDHIWsOGY2Iye%2FeEaE%2B2xO3omPqex5%2FzN184lM0iOCQP3PODICkEiMcUrGrgblJRfgz0GKjkoheQyuBn%2BlGQYVshQoZ2nptKfGzKxmGTAboXhEd1b1gO%2B3yYdYwaUHA%2FMc6xAoUwThKncrIX3AMJfyKdHV04w143kiTuGU9QHOMHjoM4gDo3TLott3NaCjADgwF7uBowGeevQg0s%2FsD0cSETvAYhzB4yKUV9czHfMY4EiR8R5QuBehwRnGZIrTw6Yu4nV%2B%2F8msGT9q6XxS67peKXQA2cZI6hE2W2Kjp4Pb0XMBxKpTrWrM%2Bx%2B61yS7YgV1GIlm%2B5AN58zWbgzfy25LW8bQipWTDQKt3aPWpu4NHofEB%2F%2Fr0ZfbvF%2Bg8xk9Pz9%2BiG%2BtcNvD%2FpViJ9uE4VoLaKqOtmuQmNm0bjOoNMbpxlZvimwNHNSPoOXCoimreTNvSDhXW9%2FIgJvNxQI7t3VXsU4xqcunhAZcDygEi7z4DV9ee0RwS73qCfVOT4hBDGXs2G%2FKrYn47oAKDEjf2jxnOOm7iBJ1bNgCAaJF3sqsx%2F%2F2MIoJiBle6sXUNj%2FhkfjgOUvYDuOxPoB%2FyLsI%2BGGI3H5xJXbuNIvY5QHHs4zABh2HDvjz7uZsRLuljNBr5Qx8lS0ymBtm6GQ7p0tOFnIGGbUwA1dcwKdC1TdkIOHqT6mXZ6ywAic%2BAGDPp5SqM%2BSw3vQMxVTHWpt7ywd9yftG0PV0GFD61WZp62wOYM0%2FQ2LpkxJiTtCXcm07QyHnjxIPFiZ8i7xxA7gu5wbUyR%2FRGcmeYxDrFISe%2FqTae43fIuOlSbAqAOuemKePT43Eqhz5KTvlSt3AqhlwLp7YJlJwqtmke9B6a0%2FUZg1M3kBLQCjrWhw62tJ%2BatpDrT%2FYXjbxpqVxT%2B7UDOauhNmPbXZN%2BXa5Jd%2Byu69YzY27XadQ3WfVIBdt9E7gu32Q61aB9TbBhHI1RpX10L94%2BAlApZ7vycalhp9Rq4W3%2FsuquuXl1SGSoWdu3rOqW95kF8g11%2BLqq%2BpvJr4pcWInm6GpRpwhn7ak%2F%2BwX0oE2OT7ewuienbqucKlzfZe3bVjjttcrpCddW94pqFLVVS89dXUPlVTXmF1Ze3e90DirxSIMvt27wmxcd8duVAgmL%2BLsaaDvoB3LNUXVCjpgPYaP6%2BUFZU2dIRMn5GVKUDqyRSDm7M%2Fd%2BJ79qPdNQ6wFodP%2FJNc1aauDU1AJjuxqAJGF4RYpgm9XXq1WlbaA1WhK4%2FMyLbufpydMyxWdRsN4v7rAlH9g26tkbPrtavl5NywdqOED9yiyfzvZbVonZaPry00Qj1m%2BVQN9RF9yaunCRVaX9DIJzej4wM7un%2FJbn%2Bb%2B8uZfaVNLphia7kaO9uqnWGVVG5xA6U7Qh7Bvx%2B1fZCu0fxFBkv78S7M2GiIt%2B60M%2B%2FuHHDPJFs2nglFMiFESc237vsstPfCCd%2BLxMihZsGNfCfmdVBE3VM8JM5d4SBSXJc%2FnwOSIonV0sly%2BTP7%2Bw%2FF8aWtBQWz%2BehrJm%2Ftf9abko%2FxcJxsNP
-->
```

**Comment by jessicadaugherty** [comment]
@Olshansk even better. I'll request to add that soon and tag you. Sorry, not a dev so thanks for your help and patience.

**Comment by Olshansk** [comment]
@jessicadaugherty I was navigating through the code so I figured to just get it out of the way here: https://github.com/pokt-foundation/docs/pull/20

**Pull request merged**
