### PR TITLE
V1 Overview & Utility Updates

### PR DESCRIPTION
**Pull request by Olshansk**
- Added a diagram showing a high level simplified overview of a relay comparison between V0 and V1 with the help of @rem1niscence 
- Minor updates/edits to the V1 overview and utility docs

### CODE REVIEW

**Comment by Olshansk** [comment]
@rem1niscence thanks for the feedback. Just wanted to summarize the changes you suggested so I don't miss anything:

1. Add an `L2 step` called `cherry picker selects best node` and a note saying "that after the best node out of the 24 selected is found, all relays are sent there".
2. Change `step 6` (the altruist) to a `backup step` and add a note saying "only on servicer failure".

Is that correct?

**Comment by rem1niscence** [comment]
> 1. Add an L2 step called cherry picker selects best node and a note saying "that after the best node out of the 24 selected is found, all relays are sent there"

Simply remove the 'all' as is only one cherry pick per request, could rephrase as "that after the best node out of the 24 selected is found, **the relay is sent there**"

> Change step 6 (the altruist) to a backup step and add a note saying "only on servicer failure".

exactly that 💯

**Comment by Olshansk** [comment]
> Simply remove the 'all' as is only one cherry pick per request

So the cherry picker ranks all the nodes in a session on every relay? For example, if my app will send 1000 relays in one session, that will be 1000 "pings" & sorts of complexity O(24)?

**Comment by rem1niscence** [comment]
yes but the ping amount is lower, the cherry picker cache only maintain data from maximum 500 requests per node chosen pseudo-random  and is pruned when it goes over that and sorts over those values, so the maximum value to sort through is 500 * NODES_PER_SESSION = 24 as of right now

**Comment by blockjoe** [comment]
Once the diagram is updated to reflect what @rem1niscence suggested, I think it would be helpful to break-up the diagram into two separate images. Then instead of the section for this diagram living below the More Details section, we can move it up above the roadmap section, and then explain any details that might need some further explanation in bullets/numbered.

**Comment by Olshansk** [comment]
Updated.

@blockjoe @jacklaing PTAL.

**Comment by Olshansk** [comment]
I've merged the changes in this PR since it is still an improvement over what we had before, but I plan to follow up with another PR next week where I will also upload the the source files to the figjams so we (and the community) and all update them.

**Comment by Olshansk** [comment]
Source files submitted here: https://github.com/pokt-foundation/docs/pull/18.

**Pull request merged**
